# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GForms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answere_type', models.CharField(max_length=50, verbose_name='Answere Type')),
            ],
        ),
    ]
