# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GForms', '0007_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Answere')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GForms.Forms')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GForms.question_answer')),
            ],
        ),
    ]
