# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GForms', '0008_form_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_response',
            old_name='question',
            new_name='question_id',
        ),
    ]
