# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GForms', '0009_auto_20170526_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_response',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form_response',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='form_response',
        ),
    ]
