# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GForms', '0010_auto_20170526_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answere', models.CharField(blank=True, max_length=100, null=True, verbose_name='Answere')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GForms.question_answer')),
            ],
        ),
        migrations.CreateModel(
            name='form_response_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GForms.Forms')),
            ],
        ),
        migrations.AddField(
            model_name='form_response',
            name='response_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GForms.form_response_id'),
        ),
    ]
